name: Generate sing-box routing rules

on:
  workflow_dispatch:
  schedule:
    - cron: "20 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 'stable'
          cache: false

      - name: Set ENV variables
        run: |
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "RELEASE_DATE=$(date +'%F %T %Z')" >> $GITHUB_ENV

      - name: Generate geosite.db file
        run: |
          mkdir -p release
          git clone https://github.com/chocolate4u/Iran-singbox-db-rules.git
          cd Iran-singbox-db-rules
          go run -v .
          sha256sum geosite.db > geosite.db.sha256sum
          cp geosite.db ../release
          cp geosite.db.sha256sum ../release
          
      - name: Generate Release Notes
        run: | 
          echo "* Updated on ${{ env.RELEASE_DATE }}" > RELEASE_NOTES
          echo "* Based on [Iran-v2ray-dat-rules](https://github.com/chocolate4u/Iran-v2ray-dat-rules)" >> RELEASE_NOTES

      - name: Release and upload assets
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          body_path: RELEASE_NOTES
          draft: false
          prerelease: false
          files: |
            ./release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
